### ISSUE TITLE
Adding Javascript without attributes

### ISSUE THREAD

**Issue by husseinalhammad** [Pipits/pipit-pinion#2]
Adding Javascript without setting attributes result in a notice and a warning:

```
Notice: Undefined index: attrs in /.../perch/addons/feathers/pipit_pinion/lib/PipitPinion_Helper.class.php on line 159

Warning: Invalid argument supplied for foreach() in /.../perch/addons/feathers/pipit_pinion/lib/PipitPinion_Helper.class.php on line 159
```

**Comment by vdecree** [comment]
Was just about to log this. Getting the same issue trying to do:

`perch_get_javascript(['cache-bust' => true]);`

**Comment by husseinalhammad** [comment]
Sorry about this @vdecree! 

You can now download [v1.1.1](https://github.com/Pipits/pipit-pinion/releases/tag/v1.1.1) which fixes this bug.
